### ISSUE TITLE
Can't run npm start

### ISSUE THREAD

**Issue by unbrandedhuman** [graphnote-app/graphnote-api#1]
I get this error:

[Nest] 2309  - 08/29/2023, 9:36:07 PM   ERROR [ExceptionHandler] connect ECONNREFUSED ::1:5432
Error: connect ECONNREFUSED ::1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1532:16)

when running 
"npm start"

**Comment by hpennington** [comment]
Hi @unbrandedhuman! You will need a postgresql instance running on port 5432, and you will need to run the seed.sql script to initialize the database.

**Comment by unbrandedhuman** [comment]
Error here: [Nest] 38812  - 09/13/2023, 6:44:00 PM   ERROR [NestApplication] Error: listen EADDRINUSE: address already in use :::3000 +4ms
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1774:16)
    at listenInCluster (node:net:1822:12)
    at Server.listen (node:net:1910:7)
    at ExpressAdapter.listen (/Users/cherriesareodd/Documents/graphnote-api/node_modules/@nestjs/platform-express/adapters/express-adapter.js:68:32)
    at /Users/cherriesareodd/Documents/graphnote-api/node_modules/@nestjs/core/nest-application.js:166:30
    at new Promise (<anonymous>)
    at NestApplication.listen (/Users/cherriesareodd/Documents/graphnote-api/node_modules/@nestjs/core/nest-application.js:155:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at bootstrap (/Users/cherriesareodd/Documents/graphnote-api/src/main.ts:6:3)
